vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        media_object:
            uri_prefix: 'https://res.cloudinary.com/dihyybd7h/image/upload/media_objects'
            upload_destination: default.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
