services:
    php:
        container_name: ${DOCKER_PROJECT_NAME}_php
        build: ./docker/php
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            # if you use supervisor
            #- ./docker/php/supervisor/messenger-worker.conf:/etc/supervisor/conf.d/messenger-worker.conf
        depends_on:
            - db

    nginx:
        container_name: ${DOCKER_PROJECT_NAME}_nginx
        image: nginx:1.28.0
        restart: unless-stopped
        volumes:
            - ./docker/nginx/logs:/var/log/nginx
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - db
        ports:
            - 127.0.0.1:${DOCKER_NGINX_PORT}:80

    db:
        image: mariadb:11.7.2
        container_name: ${DOCKER_PROJECT_NAME}_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DOCKER_PROJECT_NAME}
        volumes:
            # - ./sql:/sql
            - ./docker/mysql/db:/var/lib/mysql
        ports:
            - 127.0.0.1:${DOCKER_DATABASE_PORT}:3306  # use 5432 for pgsql


    #    redis:
    #        image: redis:7.4.4-alpine
    #        restart: unless-stopped
    #        container_name: ${DOCKER_PROJECT_NAME}_redis
